#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  Test Suite: Embedded CLI (generated by get-kortix.sh)                     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

ROOT_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
SCRIPT="$ROOT_DIR/scripts/get-kortix.sh"

PASS=0; FAIL=0; TOTAL=0

pass() { PASS=$((PASS+1)); TOTAL=$((TOTAL+1)); printf "\033[0;32m  ✓ %s\033[0m\n" "$1"; }
fail() { FAIL=$((FAIL+1)); TOTAL=$((TOTAL+1)); printf "\033[0;31m  ✗ %s\033[0m\n" "$1"; }

echo ""
echo "  Testing embedded CLI helper"
echo "  ════════════════════════════════"
echo ""

# Extract the embedded CLI from get-kortix.sh (between CLIPATH markers)
CLI_CONTENT=$(sed -n "/cat > .*\/kortix.*<< 'CLIPATH'/,/^CLIPATH/p" "$SCRIPT" | sed '1d;$d')

if [ -z "$CLI_CONTENT" ]; then
  fail "could not extract embedded CLI from get-kortix.sh"
  echo ""; echo "  0/$TOTAL passed"; echo ""
  exit 1
fi

pass "embedded CLI extracted from get-kortix.sh"

# Write it to a temp file so we can test it
TMP_CLI=$(mktemp)
echo "$CLI_CONTENT" > "$TMP_CLI"
chmod +x "$TMP_CLI"

# --- CLI has shebang ---
if head -1 "$TMP_CLI" | grep -q '#!/usr/bin/env bash'; then
  pass "CLI has bash shebang"
else
  fail "CLI has bash shebang"
fi

# --- CLI has set -euo pipefail ---
if grep -q 'set -euo pipefail' "$TMP_CLI"; then
  pass "CLI has strict mode (set -euo pipefail)"
else
  fail "CLI has strict mode (set -euo pipefail)"
fi

# --- CLI has all required commands ---
for cmd in start stop restart logs status update setup; do
  if grep -q "${cmd})" "$TMP_CLI"; then
    pass "CLI has '${cmd}' command"
  else
    fail "CLI has '${cmd}' command"
  fi
done

if grep -q 'credentials)' "$TMP_CLI"; then
  pass "CLI has 'credentials' command"
else
  fail "CLI has 'credentials' command"
fi

# --- CLI has mode detection ---
if grep -q '_mode()' "$TMP_CLI"; then
  pass "CLI has mode detection (_mode function)"
else
  fail "CLI has mode detection (_mode function)"
fi

# --- CLI has URL helper ---
if grep -q '_url()' "$TMP_CLI"; then
  pass "CLI has URL helper (_url function)"
else
  fail "CLI has URL helper (_url function)"
fi

# --- CLI has help/default case ---
if grep -q '\*)' "$TMP_CLI"; then
  pass "CLI has help/default handler"
else
  fail "CLI has help/default handler"
fi

# --- CLI uses docker compose (not docker-compose) ---
if grep -q 'docker compose' "$TMP_CLI" && ! grep -q 'docker-compose ' "$TMP_CLI"; then
  pass "CLI uses 'docker compose' (v2 syntax)"
else
  fail "CLI uses 'docker compose' (v2 syntax)"
fi

# --- CLI can rebuild local images from source ---
if grep -q '_rebuild_local_images()' "$TMP_CLI" && grep -q 'build-local-images.sh' "$TMP_CLI"; then
  pass "CLI can rebuild local images from source"
else
  fail "CLI can rebuild local images from source"
fi

# --- CLI does not reference git ---
if ! grep -q 'git pull\|git clone' "$TMP_CLI"; then
  pass "CLI has no git references"
else
  fail "CLI has no git references"
fi

# --- CLI does not reference docker-compose.local.yml ---
if ! grep -q 'docker-compose.local.yml' "$TMP_CLI"; then
  pass "CLI does not reference docker-compose.local.yml"
else
  fail "CLI does not reference docker-compose.local.yml"
fi

# --- No declare -A ---
if ! grep -q 'declare -A' "$TMP_CLI"; then
  pass "CLI has no declare -A (bash 3.x safe)"
else
  fail "CLI has no declare -A (bash 3.x safe)"
fi

# --- VPS mode: start command shows domain-based URL ---
if grep -q 'vps.*Dashboard\|Dashboard.*_url' "$TMP_CLI" || grep -q '_url' "$TMP_CLI"; then
  pass "CLI start shows domain URL in VPS mode"
else
  fail "CLI start shows domain URL in VPS mode"
fi

# Clean up
rm -f "$TMP_CLI"

# ── Summary ──
echo ""
echo "  ────────────────────────────────"
if [ "$FAIL" -eq 0 ]; then
  printf "\033[0;32m  All %d tests passed\033[0m\n" "$TOTAL"
else
  printf "\033[0;31m  %d/%d tests failed\033[0m\n" "$FAIL" "$TOTAL"
fi
echo ""

exit "$FAIL"
