// Main exports
export { createDb, type Database } from './client';
export * as schema from './schema';

// Re-export frequently used schemas and types for convenience
export {
  // Schema namespace
  kortixSchema,
  // Enums
  sandboxStatusEnum,
  executionStatusEnum,
  sessionModeEnum,
  deploymentStatusEnum,
  deploymentSourceEnum,
  channelTypeEnum,
  sessionStrategyEnum,
  apiKeyStatusEnum,
  apiKeyTypeEnum,
  // Kortix tables — accounts
  accounts,
  accountMembers,
  accountRoleEnum,
  accountsRelations,
  accountMembersRelations,
  // Kortix tables
  sandboxes,
  triggers,
  executions,
  deployments,
  channelConfigs,
  channelSessions,
  channelMessages,
  channelIdentityMap,
  kortixApiKeys,
  integrations,
  sandboxIntegrations,
  serverEntries,
  // Enums (integrations)
  integrationStatusEnum,
  // Relations
  sandboxesRelations,
  triggersRelations,
  executionsRelations,
  deploymentsRelations,
  channelConfigsRelations,
  channelSessionsRelations,
  channelMessagesRelations,
  channelIdentityMapRelations,
  kortixApiKeysRelations,
  integrationsRelations,
  sandboxIntegrationsRelations,
  // Billing / Credits (moved from public → kortix schema)
  billingCustomers,
  creditAccounts,
  creditLedger,
  creditUsage,
  accountDeletionRequests,
  creditPurchases,
  // Tunnel
  tunnelStatusEnum,
  tunnelCapabilityEnum,
  tunnelPermissionStatusEnum,
  tunnelPermissionRequestStatusEnum,
  tunnelConnections,
  tunnelPermissions,
  tunnelPermissionRequests,
  tunnelAuditLogs,
  tunnelConnectionsRelations,
  tunnelPermissionsRelations,
  tunnelPermissionRequestsRelations,
  tunnelAuditLogsRelations,
  // WoA
  woaPostTypeEnum,
  woaPosts,
  // Platform User Roles
  platformRoleEnum,
  platformUserRoles,
  // Access Control
  accessRequestStatusEnum,
  platformSettings,
  accessAllowlist,
  accessRequests,
} from './schema/kortix';

export type {
  ChannelCredentials,
  ChannelPlatformConfig,
  ChannelPlatformUser,
  TunnelMachineInfo,
  TunnelFilesystemScope,
  TunnelShellScope,
  TunnelNetworkScope,
  TunnelPermissionScope,
} from './schema/kortix';

// Public/basejump tables
export {
  apiKeys,
  accountUser,
} from './schema/public';

export type {
  Account,
  AccountMember,
  NewAccount,
  NewAccountMember,
  Sandbox,
  Trigger,
  Execution,
  NewSandbox,
  NewTrigger,
  NewExecution,
  ApiKey,
  CreditAccount,
  AccountUser,
  NewApiKey,
  SandboxSelect,
  TriggerSelect,
  ExecutionSelect,
  ChannelConfig,
  ChannelSession,
  ChannelMessage,
  ChannelIdentity,
  NewChannelConfig,
  NewChannelSession,
  NewChannelMessage,
  NewChannelIdentity,
  KortixApiKey,
  NewKortixApiKey,
  Integration,
  NewIntegration,
  SandboxIntegration,
  NewSandboxIntegration,
  ServerEntry,
  NewServerEntry,
  TunnelConnection,
  NewTunnelConnection,
  TunnelPermission,
  NewTunnelPermission,
  TunnelPermissionRequest,
  NewTunnelPermissionRequest,
  TunnelAuditLog,
  NewTunnelAuditLog,
  WoaPost,
  NewWoaPost,
} from './types';
