#!/bin/sh
# install-channel-clis.sh — Install all Kortix CLI wrappers into /usr/local/bin.
#
# All wrappers point to immutable runtime code under /ephemeral/kortix-master/.
# This runs at container startup so CLIs always reflect the current build.
#
# CLIs installed:
#   ktelegram  — Telegram bot API CLI (channels/telegram.ts)
#   kslack     — Slack Web API CLI (channels/slack.ts)
#   kchannel   — Channel management CLI (channels/kchannel.ts)
#   kconnectors — Connector management CLI (channels/kconnectors.ts)
#   kpipedream — Pipedream OAuth integration CLI (channels/kpipedream.ts)

set -eu

CHANNELS_DIR="/ephemeral/kortix-master/channels"
INSTALL_WRAPPER() {
  name="$1"
  target="$2"

  if [ ! -f "$target" ]; then
    echo "[channel-clis] SKIP: $name ($target not found)" >&2
    return 0
  fi

  cat >"/usr/local/bin/$name" <<WRAPPER
#!/bin/sh
# Wrapper for: $target
# Generated by install-channel-clis.sh — do not edit manually
exec bun run "$target" "\$@"
WRAPPER
  chmod +x "/usr/local/bin/$name"
  echo "[channel-clis] Installed: $name"
}

# ── Channel CLIs ──────────────────────────────────────────────────────────────

INSTALL_WRAPPER ktelegram  "${CHANNELS_DIR}/telegram.ts"
INSTALL_WRAPPER kslack     "${CHANNELS_DIR}/slack.ts"
INSTALL_WRAPPER kchannel   "${CHANNELS_DIR}/kchannel.ts"

# ── Integration CLIs ─────────────────────────────────────────────────────────

INSTALL_WRAPPER kconnectors "${CHANNELS_DIR}/kconnectors.ts"
INSTALL_WRAPPER kpipedream  "${CHANNELS_DIR}/kpipedream.ts"

echo "[channel-clis] Done. Available: ktelegram kslack kchannel kconnectors kpipedream"
