/**
 * Orphan Tool-Call Fixer Plugin
 *
 * Automatically repairs orphaned tool_use blocks that lack a corresponding
 * tool_result in the next message. This happens when a tool execution is
 * aborted mid-flight (e.g. user cancellation, timeout, crash) and the
 * session is resumed — the Anthropic API rejects the conversation because
 * every tool_use must have a matching tool_result.
 *
 * Strategy: In the `experimental.chat.messages.transform` hook (runs before
 * every LLM call), scan the message array for assistant messages containing
 * tool parts. For each tool_use callID, verify a matching tool_result exists
 * in the immediately following user message. If missing, remove the orphaned
 * tool part from the assistant message (along with its preceding text part
 * that served as the tool's preamble, when safe to do so).
 *
 * This is a pure in-memory transform — the database is never modified.
 */

import type { Plugin } from "@opencode-ai/plugin"

// ── Types matching the transform hook's message shape ────────────────────────

interface ChatMessagePart {
	type?: string
	callID?: string
	tool?: string
	state?: { status?: string; error?: string; input?: Record<string, unknown> }
	text?: string
	[key: string]: unknown
}

interface ChatMessage {
	info?: {
		role?: string
		id?: string
		sessionID?: string
		[key: string]: unknown
	}
	parts?: ChatMessagePart[]
	[key: string]: unknown
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Known OpenCode abortion error strings (lowercased, trimmed).
 *
 * These are generated by OpenCode itself when a tool execution is cancelled
 * (user pressed Escape, session interrupted, question dismissed, etc.).
 * They never carry meaningful tool output — the tool never actually ran.
 *
 * We match these exactly rather than doing substring matching to avoid
 * accidentally stripping legitimate tool errors whose error message happens
 * to contain words like "aborted" or "timeout".
 */
const ABORT_ERROR_EXACT: ReadonlySet<string> = new Set([
	"tool execution aborted",
	"aborterror: the operation was aborted.",
	"the user dismissed this question",
])

/**
 * Check if a tool part is an orphaned aborted call:
 * - type is "tool" with a callID
 * - status is "error"
 * - error string exactly matches a known OpenCode abort message
 *
 * In OpenCode's internal format, tool parts with status "completed" include
 * both the call and the result in one part. Aborted ones only have the call
 * half — which the Anthropic API sees as a tool_use without a tool_result.
 */
function isAbortedToolPart(part: ChatMessagePart): boolean {
	if (part.type !== "tool" || !part.callID) return false
	const state = part.state
	if (!state) return false
	if (state.status !== "error") return false

	const error = (state.error ?? "").toLowerCase().trim()
	return ABORT_ERROR_EXACT.has(error)
}

// ── Plugin ───────────────────────────────────────────────────────────────────

const OrphanToolFixerPlugin: Plugin = async (_ctx) => {
	return {
		"experimental.chat.messages.transform": async (_input, output) => {
			const messages = output.messages as ChatMessage[]
			if (!messages?.length) return

			let totalRemoved = 0

			for (const message of messages) {
				if (message.info?.role !== "assistant") continue
				if (!Array.isArray(message.parts) || message.parts.length === 0) continue

				// Find orphaned tool parts and remove them
				const originalLength = message.parts.length
				message.parts = message.parts.filter((part) => {
					if (isAbortedToolPart(part)) {
						return false // Remove orphaned aborted tool calls
					}
					return true
				})

				const removed = originalLength - message.parts.length
				if (removed > 0) {
					totalRemoved += removed

					// If the message is now empty (all parts were orphaned tools
					// plus maybe step-start/step-finish), keep at least the
					// non-tool parts. If there are truly no parts left, add a
					// minimal text part so the message isn't empty.
					const hasContent = message.parts.some(
						(p) =>
							p.type === "text" ||
							p.type === "tool" ||
							p.type === "reasoning",
					)
					if (!hasContent && message.parts.length === 0) {
						message.parts = [
							{
								type: "text",
								text: "(continued)",
							},
						]
					}
				}
			}

			if (totalRemoved > 0) {
				console.error(
					`[orphan-tool-fixer] Removed ${totalRemoved} orphaned aborted tool call(s) from message stream`,
				)
			}
		},
	}
}

export default OrphanToolFixerPlugin
