#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  Kortix — One-Click Install                                               ║
# ║                                                                            ║
# ║  curl -fsSL https://get.kortix.ai/install | bash                           ║
# ║                                                                            ║
# ║  Requirement: Docker Desktop. That's it.                                   ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

set -euo pipefail

# ─── Colors (ANSI-C quoting so escape bytes are real) ────────────────────────
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'; CYAN=$'\033[0;36m'; BOLD=$'\033[1m'
DIM=$'\033[2m'; NC=$'\033[0m'

info()    { echo "  ${BLUE}[INFO]${NC} $*"; }
success() { echo "  ${GREEN}[OK]${NC}   $*"; }
warn()    { echo "  ${YELLOW}[WARN]${NC} $*"; }
error()   { echo "  ${RED}[ERR]${NC}  $*" >&2; }
fatal()   { error "$*"; exit 1; }

# ─── Config ──────────────────────────────────────────────────────────────────
INSTALL_DIR="${KORTIX_HOME:-$HOME/.kortix}"
FRONTEND_IMAGE="kortixmarko/kortix-frontend:latest"
API_IMAGE="kortixmarko/kortix-api:latest"
SANDBOX_IMAGE="kortixmarko/sandbox:latest"
CLI_SOURCE_URL="https://raw.githubusercontent.com/kortix-ai/computer/main/scripts/get-kortix.sh"

# ─── Helpers ─────────────────────────────────────────────────────────────────
open_browser() {
  local url="$1"
  if command -v open &>/dev/null; then
    open "$url" 2>/dev/null || true
  elif command -v xdg-open &>/dev/null; then
    xdg-open "$url" 2>/dev/null || true
  elif command -v wslview &>/dev/null; then
    wslview "$url" 2>/dev/null || true
  fi
}

# ─── Banner ──────────────────────────────────────────────────────────────────
banner() {
  echo ""
  echo "${BOLD}${CYAN}"
  cat << 'EOF'
   _  __         _   _
  | |/ /___  _ _| |_(_)_ __
  | ' </ _ \| '_|  _| \ \ /
  |_|\_\___/|_|  \__|_/_\_\
EOF
  echo "${NC}"
  echo "  ${DIM}One-Click Installer${NC}"
  echo ""
}

# ─── Preflight ───────────────────────────────────────────────────────────────
preflight() {
  info "Checking prerequisites..."
  echo ""

  command -v docker &>/dev/null || fatal "Docker is required. Get it at: https://docs.docker.com/get-docker/"
  success "Docker installed"

  docker info &>/dev/null 2>&1 || fatal "Docker is not running. Start Docker Desktop and try again."
  success "Docker is running"

  docker compose version &>/dev/null 2>&1 || fatal "Docker Compose v2 is required. Included with Docker Desktop."
  success "Docker Compose available"

  echo ""
}

# ─── Add to PATH ─────────────────────────────────────────────────────────────
setup_path() {
  # 1. Try to symlink into /usr/local/bin (works immediately, no shell restart)
  if [ -d "/usr/local/bin" ] && [ -w "/usr/local/bin" ]; then
    ln -sf "$INSTALL_DIR/kortix" /usr/local/bin/kortix 2>/dev/null && {
      success "Linked 'kortix' → /usr/local/bin/kortix"
      return
    }
  fi

  # 2. Fallback: add to shell rc
  local shell_rc=""
  case "${SHELL:-}" in
    */zsh)  shell_rc="$HOME/.zshrc" ;;
    */bash) shell_rc="$HOME/.bashrc" ;;
    *)      shell_rc="$HOME/.profile" ;;
  esac

  if [ -f "$shell_rc" ] && grep -q "$INSTALL_DIR" "$shell_rc" 2>/dev/null; then
    return  # already in PATH
  fi

  echo "" >> "$shell_rc"
  echo "# Kortix CLI" >> "$shell_rc"
  echo "export PATH=\"$INSTALL_DIR:\$PATH\"" >> "$shell_rc"
  success "Added 'kortix' to PATH (restart terminal or: source $shell_rc)"
}

# ─── Write files ─────────────────────────────────────────────────────────────
write_compose() {
  info "Writing docker-compose.yml..."

  cat > "$INSTALL_DIR/docker-compose.yml" << COMPOSE
# Kortix — auto-generated by get-kortix.sh
services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_ENV_MODE=local
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8008/v1
      - NEXT_PUBLIC_OPENCODE_URL=http://localhost:14000
    depends_on:
      kortix-api:
        condition: service_started
    restart: unless-stopped

  kortix-api:
    image: ${API_IMAGE}
    ports:
      - "8008:8008"
    environment:
      - ENV_MODE=local
      - PORT=8008
      - SANDBOX_PROVIDER=local_docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - KORTIX_URL=http://kortix-api:8008/v1/router
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sandbox:
    image: ${SANDBOX_IMAGE}
    container_name: kortix-sandbox
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/
      - TITLE=Kortix Sandbox
      - OPENCODE_CONFIG_DIR=/opt/opencode
      - OPENCODE_PERMISSION={"*":"allow"}
      - DISPLAY=:1
      - LSS_DIR=/workspace/.lss
      - KORTIX_WORKSPACE=/workspace
      - KORTIX_API_URL=http://kortix-api:8008/v1/router
      - SANDBOX_ID=kortix-sandbox
      - PROJECT_ID=local
      - ENV_MODE=local
      - SANDBOX_PORT_MAP={"8000":"14000","3111":"14001","6080":"14002","6081":"14003","3210":"14004","9223":"14005","9224":"14006"}
    env_file:
      - .env
    volumes:
      - sandbox-workspace:/workspace
      - sandbox-secrets:/app/secrets
    ports:
      - "14000:8000"
      - "14001:3111"
      - "14002:6080"
      - "14003:6081"
      - "14004:3210"
      - "14005:9223"
      - "14006:9224"
    shm_size: "2gb"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/kortix/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  sandbox-workspace:
  sandbox-secrets:
COMPOSE

  success "Saved docker-compose.yml"
}

write_env() {
  if [ ! -f "$INSTALL_DIR/.env" ]; then
    echo "# Kortix — configure via: kortix setup" > "$INSTALL_DIR/.env"
  fi
}

write_cli() {
  cat > "$INSTALL_DIR/kortix" << 'CLIPATH'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

G=$'\033[0;32m'; C=$'\033[0;36m'; B=$'\033[1m'; D=$'\033[2m'; N=$'\033[0m'
VERSION="0.1.0"

_open() {
  if command -v open &>/dev/null; then open "$1" 2>/dev/null
  elif command -v xdg-open &>/dev/null; then xdg-open "$1" 2>/dev/null
  elif command -v wslview &>/dev/null; then wslview "$1" 2>/dev/null
  fi
}

case "${1:-help}" in
  start)
    docker compose up -d
    echo ""
    echo "  ${G}Kortix is running!${N}"
    echo "  Dashboard:  ${B}http://localhost:3000${N}"
    echo "  API:        ${B}http://localhost:8008${N}"
    echo "  Sandbox:    ${B}http://localhost:14000${N}"
    echo ""
    ;;
  stop)
    docker compose down
    echo "  ${G}Stopped.${N}"
    ;;
  restart)
    docker compose down
    docker compose up -d
    echo "  ${G}Restarted.${N}"
    ;;
  logs)
    shift
    docker compose logs -f "$@"
    ;;
  status)
    docker compose ps
    ;;
  setup)
    echo ""
    echo "  ${C}Opening setup in browser...${N}"
    _open "http://localhost:3000/setup"
    echo ""
    echo "  ${D}If it didn't open, go to:${N}"
    echo "  ${B}http://localhost:3000/setup${N}"
    echo ""
    echo "  ${D}Or edit .env directly:${N}"
    echo "    nano ${DIR}/.env"
    echo "    kortix restart"
    echo ""
    ;;
  update)
    echo "  ${C}Pulling latest images...${N}"
    docker compose pull
    docker compose down
    docker compose up -d
    echo "  ${G}Updated to latest.${N}"
    ;;
  uninstall)
    echo ""
    echo "  ${B}Uninstall Kortix${N}"
    echo ""

    # Stop containers
    echo "  ${C}Stopping services...${N}"
    docker compose down 2>/dev/null || true

    # Ask about Docker volumes (workspace data)
    echo ""
    printf "  Delete workspace data (Docker volumes)? [y/N]: "
    read -r del_volumes
    if echo "$del_volumes" | grep -qi '^y'; then
      docker compose down -v 2>/dev/null || true
      # Also remove the named container if lingering
      docker rm -f kortix-sandbox 2>/dev/null || true
      echo "  ${G}Volumes removed.${N}"
    else
      echo "  ${D}Keeping volumes (your workspace data is safe).${N}"
    fi

    # Ask about Docker images
    echo ""
    printf "  Delete Docker images? [y/N]: "
    read -r del_images
    if echo "$del_images" | grep -qi '^y'; then
      docker rmi kortixmarko/kortix-frontend:latest 2>/dev/null || true
      docker rmi kortixmarko/kortix-api:latest 2>/dev/null || true
      docker rmi kortixmarko/sandbox:latest 2>/dev/null || true
      echo "  ${G}Images removed.${N}"
    else
      echo "  ${D}Keeping images.${N}"
    fi

    # Remove /usr/local/bin symlink (if created by setup_path)
    if [ -L "/usr/local/bin/kortix" ]; then
      rm -f /usr/local/bin/kortix 2>/dev/null || true
      echo "  ${G}Removed /usr/local/bin/kortix symlink.${N}"
    fi

    # Remove PATH entry from shell rc files
    for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.profile"; do
      if [ -f "$rc" ] && grep -q "$DIR" "$rc" 2>/dev/null; then
        grep -v "$DIR" "$rc" | grep -v "# Kortix CLI" > "${rc}.tmp" && mv "${rc}.tmp" "$rc"
      fi
    done

    # Remove install directory
    echo ""
    echo "  ${C}Removing ${DIR}...${N}"
    rm -rf "$DIR"

    echo ""
    echo "  ${G}Kortix has been uninstalled.${N}"
    echo ""
    ;;
  open)
    _open "http://localhost:3000"
    ;;
  version)
    echo "  kortix ${VERSION}"
    ;;
  *)
    echo ""
    echo "  ${B}${C}Kortix CLI${N} ${D}v${VERSION}${N}"
    echo ""
    echo "  ${C}start${N}       Start all services"
    echo "  ${C}stop${N}        Stop all services"
    echo "  ${C}restart${N}     Restart all services"
    echo "  ${C}logs${N}        Tail logs (kortix logs sandbox)"
    echo "  ${C}status${N}      Show service status"
    echo "  ${C}setup${N}       Open API key configuration in browser"
    echo "  ${C}update${N}      Pull latest images & restart"
    echo "  ${C}open${N}        Open dashboard in browser"
    echo "  ${C}uninstall${N}   Remove Kortix completely"
    echo "  ${C}version${N}     Show version"
    echo ""
    ;;
esac
CLIPATH

  chmod +x "$INSTALL_DIR/kortix"
}

# ─── Pull & start ───────────────────────────────────────────────────────────
pull_and_start() {
  echo ""
  info "Pulling Docker images (this may take a few minutes)..."
  echo ""

  cd "$INSTALL_DIR"
  docker compose pull

  echo ""
  info "Starting Kortix..."
  echo ""

  docker compose up -d

  # Wait for frontend to be ready
  info "Waiting for services to start..."
  local attempts=0
  while [ $attempts -lt 30 ]; do
    if curl -sf http://localhost:3000 >/dev/null 2>&1; then
      break
    fi
    sleep 2
    attempts=$((attempts + 1))
  done

  echo ""
  echo "  ${BOLD}${GREEN}Kortix is running!${NC}"
  echo ""
  echo "  ${CYAN}Dashboard:${NC}   ${BOLD}http://localhost:3000${NC}"
  echo "  ${CYAN}API:${NC}         ${BOLD}http://localhost:8008${NC}"
  echo "  ${CYAN}Sandbox:${NC}     ${BOLD}http://localhost:14000${NC}"
  echo ""

  # Open setup page in browser
  info "Opening setup in browser..."
  open_browser "http://localhost:3000/setup"
  echo ""
  echo "  ${BOLD}Next step:${NC} Add your API keys in the browser."
  echo ""
  echo "  ${DIM}Commands:${NC}"
  echo "    ${CYAN}kortix start${NC}     Start services"
  echo "    ${CYAN}kortix stop${NC}      Stop services"
  echo "    ${CYAN}kortix setup${NC}     Configure API keys"
  echo "    ${CYAN}kortix update${NC}    Update to latest"
  echo ""
}

# ─── Main ────────────────────────────────────────────────────────────────────
main() {
  banner
  preflight

  # Existing install? Offer to just start it.
  if [ -f "$INSTALL_DIR/docker-compose.yml" ]; then
    warn "Existing installation found at $INSTALL_DIR"
    printf "  Reinstall? [y/N]: "
    read -r answer
    if [ -z "$answer" ] || ! echo "$answer" | grep -qi '^y'; then
      echo ""
      info "Starting existing installation..."
      cd "$INSTALL_DIR"
      docker compose up -d
      echo ""
      success "Kortix is running!"
      echo "  Dashboard: ${BOLD}http://localhost:3000${NC}"
      echo ""
      exit 0
    fi
    echo ""
    # Tear down old install (remove secrets volume so onboarding resets)
    info "Stopping old services..."
    cd "$INSTALL_DIR"
    docker compose down -v 2>/dev/null || true
    docker rm -f kortix-sandbox 2>/dev/null || true
    echo ""
  fi

  mkdir -p "$INSTALL_DIR"

  write_compose
  write_env
  write_cli
  setup_path
  pull_and_start
}

main "$@"
