#!/usr/bin/env bash
set -euo pipefail

# ─── Kortix env setup ───────────────────────────────────────────────────────
# Reads the root .env and generates per-service .env files.
#
# Usage:
#   ./scripts/setup-env.sh            # uses .env
#   ./scripts/setup-env.sh .env.prod  # uses a custom env file
# ─────────────────────────────────────────────────────────────────────────────

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${1:-.env}"

if [ ! -f "$ROOT_DIR/$ENV_FILE" ]; then
  echo "ERROR: $ROOT_DIR/$ENV_FILE not found."
  echo "  Create a root .env with your values (see services/kortix-api/.env.example)"
  exit 1
fi

set -a
while IFS='=' read -r key value; do
  case "$key" in
    \#*|"") continue ;;
  esac
  key="$(echo "$key" | xargs)"
  [ -z "$key" ] && continue
  export "$key=$value"
done < "$ROOT_DIR/$ENV_FILE"
set +a

e() {
  local val="${!1:-}"
  if [ -n "$val" ]; then
    echo "$val"
  else
    echo "${2:-}"
  fi
}

kv() { echo "$1=$(e "$1" "${2:-}")"; }

write_env() {
  local target="$1"
  shift
  mkdir -p "$(dirname "$ROOT_DIR/$target")"
  {
    echo "# Auto-generated by scripts/setup-env.sh — do not edit manually"
    echo "# Source: $ENV_FILE ($(date +%Y-%m-%d))"
    echo ""
    printf '%s\n' "$@"
  } > "$ROOT_DIR/$target"
  echo "  -> $target"
}

echo "Generating .env files from $ENV_FILE ..."
echo ""

write_env "services/kortix-api/.env" \
  "# Core" \
  "PORT=8008" \
  "$(kv ENV_MODE local)" \
  "$(kv INTERNAL_KORTIX_ENV dev)" \
  "$(kv KORTIX_BILLING_INTERNAL_ENABLED false)" \
  "" \
  "# Database + Supabase (REQUIRED)" \
  "$(kv DATABASE_URL)" \
  "$(kv SUPABASE_URL)" \
  "$(kv SUPABASE_SERVICE_ROLE_KEY)" \
  "" \
  "# Security (REQUIRED)" \
  "$(kv API_KEY_SECRET)" \
  "" \
  "# Sandbox" \
  "$(kv ALLOWED_SANDBOX_PROVIDERS local_docker)" \
  "$(kv DOCKER_HOST)" \
  "" \
  "# Daytona (conditional — only if daytona provider enabled)" \
  "$(kv DAYTONA_API_KEY)" \
  "$(kv DAYTONA_SERVER_URL)" \
  "$(kv DAYTONA_TARGET)" \
  "" \
  "# Integrations / Pipedream" \
  "$(kv INTEGRATION_AUTH_PROVIDER pipedream)" \
  "$(kv PIPEDREAM_CLIENT_ID)" \
  "$(kv PIPEDREAM_CLIENT_SECRET)" \
  "$(kv PIPEDREAM_PROJECT_ID)" \
  "$(kv PIPEDREAM_ENVIRONMENT development)" \
  "" \
  "# Scheduler" \
  "$(kv SCHEDULER_ENABLED true)" \
  "$(kv CRON_TICK_SECRET)" \
  "# CRON_API_URL auto-derived from PORT + DOCKER_HOST" \
  "" \
  "# LLM Providers (optional — cloud routing)" \
  "$(kv OPENROUTER_API_KEY)" \
  "$(kv OPENAI_API_KEY)" \
  "$(kv XAI_API_KEY)" \
  "$(kv GEMINI_API_KEY)" \
  "$(kv GROQ_API_KEY)" \
  "" \
  "# Search & Proxy Providers (optional)" \
  "$(kv TAVILY_API_KEY)" \
  "$(kv SERPER_API_KEY)" \
  "$(kv FIRECRAWL_API_KEY)" \
  "$(kv REPLICATE_API_TOKEN)" \
  "" \
  "# Billing (optional)" \
  "$(kv STRIPE_SECRET_KEY)" \
  "$(kv STRIPE_WEBHOOK_SECRET)" \
  "$(kv REVENUECAT_WEBHOOK_SECRET)"

write_env "apps/frontend/.env" \
  "$(kv NEXT_PUBLIC_BILLING_ENABLED false)" \
  "" \
  "$(kv NEXT_PUBLIC_SUPABASE_URL "$(e SUPABASE_URL)")" \
  "$(kv NEXT_PUBLIC_SUPABASE_ANON_KEY "$(e SUPABASE_ANON_KEY)")" \
  "" \
  "$(kv NEXT_PUBLIC_URL http://localhost:3000)" \
  "$(kv NEXT_PUBLIC_BACKEND_URL http://localhost:8008/v1)" \
  "" \
  "$(kv NEXT_PUBLIC_GOOGLE_CLIENT_ID)" \
  "$(kv NEXT_PUBLIC_POSTHOG_KEY)" \
  "$(kv KORTIX_ADMIN_API_KEY)" \
  "" \

echo ""
echo "Done! All .env files generated from $ENV_FILE"
echo ""
echo "Next steps:"
echo "  pnpm dev           # start everything"
echo "  pnpm dev:services  # start backend only"
