config:
  aws:region: us-west-2
  kortix-eks:clusterName: kortix-prod
  kortix-eks:clusterVersion: "1.31"
  kortix-eks:domain: v2-prod.kortix.com
  kortix-eks:nodeInstanceType: t3.large
  kortix-eks:nodeMinSize: "2"
  kortix-eks:nodeDesiredSize: "3"
  kortix-eks:nodeMaxSize: "6"
  kortix-eks:nodeDiskSize: "50"
  kortix-eks:appPort: "8008"
  kortix-eks:appMinReplicas: "3"
  kortix-eks:appMaxReplicas: "10"
  kortix-eks:cpuTargetUtilization: "70"
  kortix-eks:memoryTargetUtilization: "80"
  kortix-eks:cpuRequest: 250m
  kortix-eks:memoryRequest: 512Mi
  kortix-eks:cpuLimit: "1000m"
  kortix-eks:memoryLimit: 1Gi
  kortix-eks:acmCertificateArn: "arn:aws:acm:us-west-2:935064898258:certificate/5ddb1032-3285-48a0-8581-07f4e99df2f3"
encryptionsalt: v1:lqcy6bMwXjk=:v1:z65gmG67Uyi+12NL:94XejQfzIMrhyuuAnYULZ9pjOldamQ==
