apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kortix

resources:
  - namespace.yaml
  - services/frontend.yaml
  - services/kortix-router.yaml
  - services/kortix-auth.yaml
  - services/kortix-billing.yaml
  - services/kortix-cloud.yaml
  - services/kortix-cron.yaml
  - services/kortix-platform.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: kortix
    includeSelectors: true
